import Script from "next/script";

export default function Head() {
  return (
    <>
      <title>Personal Website</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      {/* <link rel="icon" href="/static/static/favicon.ico" /> */}
      <link
        rel="apple-touch-icon"
        sizes="180x180"
        href="/static/icons/favicon.ico"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="/static/icons/favicon.ico"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="16x16"
        href="/static/icons/favicon.ico"
      />
      <link rel="manifest" href="/static/icons/site.webmanifest" />
      {/* <Script src="https://app.embed.im/snow.js" defer></Script> */}
    </>
  );
}
